[general]
import = ["colors-wallust.toml"]

[window]
padding = { x = 16, y = 16 }
decorations = "None"
opacity = 0.6

[font]
normal = { family = "Space Mono Nerd Font Mono" }
bold = { family = "Space Mono Nerd Font Mono" }
italic = { family = "Space Mono Nerd Font Mono" }
bold_italic = { family = "Space Mono Nerd Font Mono" }
size = 13.7

[cursor]
style = { shape = "Beam", blinking = "On" }
