# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#1F191F"
foreground = "#D0B2D5"

[colors.normal]
black   = "#241D25"
red     = "#6F5D64"
green   = "#675E74"
yellow  = "#696387"
blue    = "#7D7193"
magenta = "#8981AD"
cyan    = "#8A80AA"
white   = "#D0B2D5"

[colors.bright]
black   = "#3A323B"
red     = "#6F5D64"
green   = "#675E74"
yellow  = "#696387"
blue    = "#7D7193"
magenta = "#8981AD"
cyan    = "#8A80AA"
white   = "#D0B2D5"

