[colors.primary]
background = "#1b1012"
foreground = "#f3dddf"

[colors.normal]
black   = "#574143"
red     = "#debfc2"
green   = "#ffb68f"
yellow  = "#ffb2bb"
blue    = "#ffb2bb"
magenta = "#f3dddf"
cyan    = "#ffdbde"
white   = "#a58a8c"

[colors.bright]
black   = "#745759"
red     = "#efe1e2"
green   = "#ffd7c2"
yellow  = "#ffe5e8"
blue    = "#ffe5e8"
magenta = "#ffffff"
cyan    = "#ffffff"
white   = "#bba7a8"
