[colors.primary]
background = "#121316"
foreground = "#e2e2e5"

[colors.normal]
black   = "#42474e"
red     = "#c3c7cf"
green   = "#e5b8e8"
yellow  = "#bbc8da"
blue    = "#a6caf3"
magenta = "#e2e2e5"
cyan    = "#d4e1f4"
white   = "#8d9198"

[colors.bright]
black   = "#717985"
red     = "#fcfcfc"
green   = "#ffffff"
yellow  = "#fdfdfe"
blue    = "#ffffff"
magenta = "#ffffff"
cyan    = "#ffffff"
white   = "#c3c5c8"
