# wallust.toml needs to include this
# alacritty = { template = 'alacritty.toml', target = '~/.config/alacritty/colors.toml' }
# and alacritty.toml should import that file under [general]
[colors.primary]
background = "#080D0E"
foreground = "#A8C5D0"

[colors.normal]
black   = "#0A0F10"
red     = "#516472"
green   = "#5E7480"
yellow  = "#737E72"
blue    = "#887966"
magenta = "#768A96"
cyan    = "#99A6A6"
white   = "#A8C5D0"

[colors.bright]
black   = "#212425"
red     = "#516472"
green   = "#5E7480"
yellow  = "#737E72"
blue    = "#887966"
magenta = "#768A96"
cyan    = "#99A6A6"
white   = "#A8C5D0"

