[colors.primary]
background = "#000000"
foreground = "#e6e1e6"

[colors.normal]
black   = "#49454f"
red     = "#cac4d0"
green   = "#fdb0d5"
yellow  = "#ccc2df"
blue    = "#cfbdfe"
magenta = "#e6e1e6"
cyan    = "#e6dbf9"
white   = "#948f9a"

[colors.bright]
black   = "#625d6a"
red     = "#e4e0e7"
green   = "#fee2ef"
yellow  = "#e8e3f1"
blue    = "#f4efff"
magenta = "#fdfdfd"
cyan    = "#ffffff"
white   = "#aeaab2"
