$image = /home/adwin/dotfiles/wallpaper/wallpaper/a_river_running_through_a_rocky_canyon.jpg

$background = rgba(17120dff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(362f29ff)

$inverse_primary = rgba(85530fff)

$inverse_surface = rgba(ece0d7ff)

$on_background = rgba(ece0d7ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(482900ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(2b1700ff)

$on_primary_fixed_variant = rgba(673d00ff)

$on_secondary = rgba(422c12ff)

$on_secondary_container = rgba(ffdab4ff)

$on_secondary_fixed = rgba(2a1702ff)

$on_secondary_fixed_variant = rgba(5b4226ff)

$on_surface = rgba(ece0d7ff)

$on_surface_variant = rgba(d5c3b3ff)

$on_tertiary = rgba(2d3400ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(191e00ff)

$on_tertiary_fixed_variant = rgba(424b01ff)

$outline = rgba(9e8e7fff)

$outline_variant = rgba(514538ff)

$primary = rgba(fcb96dff)

$primary_container = rgba(996420ff)

$primary_fixed = rgba(ffddbbff)

$primary_fixed_dim = rgba(fcb96dff)

$scrim = rgba(000000ff)

$secondary = rgba(e4c09cff)

$secondary_container = rgba(5b4226ff)

$secondary_fixed = rgba(ffddbbff)

$secondary_fixed_dim = rgba(e4c09cff)

$shadow = rgba(000000ff)

$source_color = rgba(996420ff)

$surface = rgba(17120dff)

$surface_bright = rgba(3f3832ff)

$surface_container = rgba(241f19ff)

$surface_container_high = rgba(2f2923ff)

$surface_container_highest = rgba(3a342eff)

$surface_container_low = rgba(201b15ff)

$surface_container_lowest = rgba(120d09ff)

$surface_dim = rgba(17120dff)

$surface_tint = rgba(fcb96dff)

$surface_variant = rgba(514538ff)

$tertiary = rgba(c1ce78ff)

$tertiary_container = rgba(6a752aff)

$tertiary_fixed = rgba(ddea91ff)

$tertiary_fixed_dim = rgba(c1ce78ff)

