$image = /home/test/dotfiles/wallpaper/wallpaper/windows-xp-bliss.jpg

$background = rgba(11131bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2e3039ff)

$inverse_primary = rgba(0153daff)

$inverse_surface = rgba(e1e2edff)

$on_background = rgba(e1e2edff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(002a77ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(00174bff)

$on_primary_fixed_variant = rgba(003ea7ff)

$on_secondary = rgba(192d62ff)

$on_secondary_container = rgba(d8dfffff)

$on_secondary_fixed = rgba(00174bff)

$on_secondary_fixed_variant = rgba(31447aff)

$on_surface = rgba(e1e2edff)

$on_surface_variant = rgba(c3c6d7ff)

$on_tertiary = rgba(55006cff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(340043ff)

$on_tertiary_fixed_variant = rgba(760b94ff)

$outline = rgba(8d90a0ff)

$outline_variant = rgba(434654ff)

$primary = rgba(b4c5ffff)

$primary_container = rgba(2663e9ff)

$primary_fixed = rgba(dbe1ffff)

$primary_fixed_dim = rgba(b4c5ffff)

$scrim = rgba(000000ff)

$secondary = rgba(b4c5ffff)

$secondary_container = rgba(31447aff)

$secondary_fixed = rgba(dbe1ffff)

$secondary_fixed_dim = rgba(b4c5ffff)

$shadow = rgba(000000ff)

$source_color = rgba(2663e9ff)

$surface = rgba(11131bff)

$surface_bright = rgba(373942ff)

$surface_container = rgba(1d1f27ff)

$surface_container_high = rgba(282a32ff)

$surface_container_highest = rgba(32343dff)

$surface_container_low = rgba(191b23ff)

$surface_container_lowest = rgba(0c0e15ff)

$surface_dim = rgba(11131bff)

$surface_tint = rgba(b4c5ffff)

$surface_variant = rgba(434654ff)

$tertiary = rgba(f2afffff)

$tertiary_container = rgba(a241beff)

$tertiary_fixed = rgba(fcd7ffff)

$tertiary_fixed_dim = rgba(f2afffff)

