
$image = /home/adwin/wallpaper/b-285.jpg
$background = rgba(171215ff)

$image = /home/adwin/wallpaper/b-285.jpg
$error = rgba(ffb4abff)

$image = /home/adwin/wallpaper/b-285.jpg
$error_container = rgba(93000aff)

$image = /home/adwin/wallpaper/b-285.jpg
$inverse_on_surface = rgba(352f32ff)

$image = /home/adwin/wallpaper/b-285.jpg
$inverse_primary = rgba(844b78ff)

$image = /home/adwin/wallpaper/b-285.jpg
$inverse_surface = rgba(ebe0e4ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_background = rgba(ebe0e4ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_error = rgba(690005ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_error_container = rgba(ffdad6ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_primary = rgba(4f1d47ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_primary_container = rgba(000000ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_primary_fixed = rgba(360531ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_primary_fixed_variant = rgba(69335fff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_secondary = rgba(40293aff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_secondary_container = rgba(fedaf1ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_secondary_fixed = rgba(291425ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_secondary_fixed_variant = rgba(583f51ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_surface = rgba(ebe0e4ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_surface_variant = rgba(d3c2cbff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_tertiary = rgba(581c19ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_tertiary_container = rgba(000000ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_tertiary_fixed = rgba(3c0707ff)

$image = /home/adwin/wallpaper/b-285.jpg
$on_tertiary_fixed_variant = rgba(75322eff)

$image = /home/adwin/wallpaper/b-285.jpg
$outline = rgba(9b8d95ff)

$image = /home/adwin/wallpaper/b-285.jpg
$outline_variant = rgba(4f434bff)

$image = /home/adwin/wallpaper/b-285.jpg
$primary = rgba(f7b1e4ff)

$image = /home/adwin/wallpaper/b-285.jpg
$primary_container = rgba(bc7cadff)

$image = /home/adwin/wallpaper/b-285.jpg
$primary_fixed = rgba(ffd7f1ff)

$image = /home/adwin/wallpaper/b-285.jpg
$primary_fixed_dim = rgba(f7b1e4ff)

$image = /home/adwin/wallpaper/b-285.jpg
$scrim = rgba(000000ff)

$image = /home/adwin/wallpaper/b-285.jpg
$secondary = rgba(dfbdd3ff)

$image = /home/adwin/wallpaper/b-285.jpg
$secondary_container = rgba(5b4154ff)

$image = /home/adwin/wallpaper/b-285.jpg
$secondary_fixed = rgba(fdd8f0ff)

$image = /home/adwin/wallpaper/b-285.jpg
$secondary_fixed_dim = rgba(dfbdd3ff)

$image = /home/adwin/wallpaper/b-285.jpg
$shadow = rgba(000000ff)

$image = /home/adwin/wallpaper/b-285.jpg
$source_color = rgba(a46796ff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface = rgba(171215ff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_bright = rgba(3e373bff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_container = rgba(231e21ff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_container_high = rgba(2e282cff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_container_highest = rgba(393337ff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_container_low = rgba(1f1a1dff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_container_lowest = rgba(110d10ff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_dim = rgba(171215ff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_tint = rgba(f7b1e4ff)

$image = /home/adwin/wallpaper/b-285.jpg
$surface_variant = rgba(4f434bff)

$image = /home/adwin/wallpaper/b-285.jpg
$tertiary = rgba(ffb3adff)

$image = /home/adwin/wallpaper/b-285.jpg
$tertiary_container = rgba(cf7972ff)

$image = /home/adwin/wallpaper/b-285.jpg
$tertiary_fixed = rgba(ffdad6ff)

$image = /home/adwin/wallpaper/b-285.jpg
$tertiary_fixed_dim = rgba(ffb3adff)

