source = ~/.config/hypr/colors.conf
background = $surface
base = $surface
alternate_base = $surface
text = $primary
accent = $secondary
accent_secondary = $tertiary
bright_text = $error
h1_size = 13
h2_size = 13
h3_size = 13
font_size = 13
icon_theme = "Papirus-Dark"
font_family = "Lilex Nerd Font"
rounding_large = 20
rounding_small = 10

