# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e7e1dd"

# Title color for boxes
theme[title]="#d7c59f"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d0c5b3"

# Background color of selected item in processes box
theme[selected_bg]="#d7c59f"

# Foreground color of selected item in processes box
theme[selected_fg]="#3a2f15"

# Color of inactive/disabled text
theme[inactive_fg]="#cec5b8"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c0cbab"

# Cpu box outline color
theme[cpu_box]="#979084"

# Memory/disks box outline color
theme[mem_box]="#979084"

# Net up/down box outline color
theme[net_box]="#979084"

# Processes box outline color
theme[proc_box]="#979084"

# Box divider line and small boxes line color
theme[div_line]="#4b463c"

# Temperature graph colors
theme[temp_start]="#d0c5b3"
theme[temp_mid]="#d7c59f"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d0c5b3"
theme[cpu_mid]="#d7c59f"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d0c5b3"
theme[free_mid]=""
theme[free_end]="#4d4638"

# Mem/Disk cached meter
theme[cached_start]="#c0cbab"
theme[cached_mid]=""
theme[cached_end]="#8a9578"

# Mem/Disk available meter
theme[available_start]="#d7c59f"
theme[available_mid]=""
theme[available_end]="#9f8f6d"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d0c5b3"
theme[download_mid]="#d7c59f"
theme[download_end]="#c0cbab"

# Upload graph colors
theme[upload_start]="#d0c5b3"
theme[upload_mid]="#d7c59f"
theme[upload_end]="#c0cbab"