hl.on("hyprland.start", function()
    hl.exec_cmd("udiskie")
    hl.exec_cmd("awww-daemon & awww restore")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("/usr/lib/xdg-desktop-portal-hyprland")
    hl.exec_cmd("waybar")
    hl.exec_cmd("waybar -c ~/.config/waybar/osd.jsonc -s ~/.config/waybar/osd.css")
    hl.exec_cmd("mako")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")
    hl.exec_cmd("wlsunset -S 6:30 -s 18:30")
    hl.exec_cmd("kanshi")
end)
