backend = "fastresize"
palette = "kmeans"
style = "light"
check_contrast = true

[templates.kitty]
template = 'kitty-colors.conf'
target = '~/.config/kitty/colors-wallust.conf'
[templates.zed]
template = 'zed.json'
target = '~/.config/zed/themes/wallust.json'
[templates.alacritty]
template = 'alacritty.toml'
target = '~/.config/alacritty/colors-wallust.toml'

[hooks]
[templated_hooks]
