cursor            #ccbdff
cursor_text_color #350097

foreground            #e6e0ec
background            #0f0d15
selection_foreground  #33285d
selection_background  #ccbefd
url_color             #ccbefd

color0  #14121a
color8  #36333c
color1  #ffb4ab
color9  #690005
color2  #ccbefd
color10 #e7deff
color3  #ffade5
color11 #ffd7ef
color4  #4d25b5
color12 #ccbdff
color5  #4a3e75
color13 #ccbefd
color6  #830c71
color14 #ffade5
color7  #cac4d6
color15 #e6e0ec

mark1_foreground #1f0060
mark1_background #e7deff
mark2_foreground #1e1146
mark2_background #e7deff
mark3_foreground #3a0031
mark3_background #ffd7ef

active_tab_foreground #350097
active_tab_background #ccbdff
inactive_tab_foreground #ffffff
inactive_tab_background #7c5ce6

active_border_color #ccbdff
inactive_border_color #350097
