cursor #bbd072

background #13140e
foreground #e4e3d8

color0 #46483a
color1 #ffb4ab
color2 #8bd79f
color3 #c2cb9e
color4 #bbd072
color5 #8bd79f
color6 #bbd072
color7 #13140e
color8 #c6c8b5
color9 #ffb4ab
color10 #8bd79f
color11 #c2cb9e
color12 #bbd072
color13 #8bd79f
color14 #bbd072
color15 #13140e

mark1_foreground #e0eabf
mark2_foreground #4c5038
mark3_foreground #e0eabf
