cursor #FCD494

background #000016
foreground #FEF4DB

color0 #000016
color1 #4FBFEF
color2 #FBB44C
color3 #98D2C6
color4 #97E798
color5 #D6EA74
color6 #FBDF99
color7 #F5E7C4
color8 #ABA189
color9 #4FBFEF
color10 #FBB44C
color11 #98D2C6
color12 #97E798
color13 #D6EA74
color14 #FBDF99
color15 #F5E7C4

mark1_foreground #FBD67A
mark2_foreground #F5DC9D
mark3_foreground #FBD67A
