cursor #bcc9ca

background #131313
foreground #e4e2e1

color0 #424848
color1 #ffb4ab
color2 #cac4d2
color3 #c3c7c7
color4 #bcc9ca
color5 #cac4d2
color6 #bcc9ca
color7 #131313
color8 #c3c7c7
color9 #ffb4ab
color10 #cac4d2
color11 #c3c7c7
color12 #bcc9ca
color13 #cac4d2
color14 #bcc9ca
color15 #131313

mark1_foreground #f5f7f7
mark2_foreground #464646
mark3_foreground #f5f7f7
